### ISSUE TITLE
bug to test with the data specified in the paper

### ISSUE THREAD

**Issue by deliangye** [AIS-Bonn/lidar_mars_registration#2] opened 2021-12-12 19:13 UTC
run the node, it gets the following issue:
![Screenshot from 2021-12-12 14-07-22](https://user-images.githubusercontent.com/12262760/145726125-d498b33e-27f6-4577-9af2-4a89b7ae549e.png)

**Comment by JanQuenzel** [comment] 2021-12-13 18:48
Hi @deliangye ,
this was caused by an incomplete clean up before source release and should be fixed now.
I further included the option to specify the config file from the subfolder ./config/
You can run it now with:
`rosrun lidar_mars_registration lidar_mars_registration_node _config_file_rel:="./config/urban_loco.cfg"`

Best, Jan

**Comment by deliangye** [comment] 2021-12-14 02:14
Thanks! Jan. 
but the application seems stuck, see:
![Screenshot from 2021-12-13 21-11-36](https://user-images.githubusercontent.com/12262760/145920376-7d729e88-0d61-4ceb-82a3-5083af255015.png)

**Comment by JanQuenzel** [comment] 2021-12-14 10:39
Hi @deliangye ,
at that time it is waiting for new incoming data. To make this more clear, I added a new message output after initialization and it should now say to which pointcloud topic it tries to subscribe.
It should now look similar to the following, e.g. with oxford cfg:
```
$ rosrun lidar_mars_registration lidar_mars_registration_node _config_file_rel:="./config/oxford.cfg"
( uptime  ) [ thread name/id]        file:line     v| 
[main thread ]  loguru.hpp:1834     0| arguments: ./lidar_mars_registration_node _config_file_rel:=./config/oxford.cfg
[main thread ]  loguru.hpp:1837     0| Current dir: ./
[main thread ]  loguru.hpp:1839     0| stderr verbosity: 2
[main thread ]  loguru.hpp:1840     0| -----------------------------------
[main thread ]  loguru.hpp:1992     0| Logging to './lidar_mars_registration_node/20211214_111504.976.log', mode: 'w', verbosity: 9
[main thread ]MarsRegistration_Node.cxx:62       0| config file: ./config/oxford.cfg
[main thread ]MarsMapWindow.cxx:88       0| MarsMapWindow: numMaps: 3
[main thread ]MarsMapWindow.cxx:88       0| MarsMapWindow: numMaps: 3
[main thread ]MarsSplineRegistrationAdaptor.cxx:205      0| Subscribed for clouds to topic: /os1_cloud_node/points
[main thread ]MarsSplineRegistrationAdaptor.cxx:241      0| Initialized. Waiting for data...

```


Depending on the bag file you are planning to play, you have to adapt the cloud_topic for the registration_adaptor in the config file. For bag files from urban_loco there are 3 different topics throughout the whole dataset. Hence, I added for each one cfg (urban_loco_ca.cfg, urban_loco_hk.cfg, urban_loco_hk0.cfg) instead of the singular urban_loco.cfg .
Best, Jan

**Comment by deliangye** [comment] 2021-12-15 16:36
thanks Jan! it is running as yours.

**Closed as completed** 2022-02-24 12:45 UTC
